# Generated by Django 5.2.7 on 2025-11-28 10:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog_Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("content", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="blog_headers/"),
                ),
                ("author", models.CharField(default="Admin", max_length=100)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("reading_time", models.PositiveIntegerField(default=2)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("travel", "Travel"),
                            ("business", "Business"),
                            ("news", "News"),
                            ("sport", "Sport"),
                        ],
                        default="travel",
                        max_length=20,
                    ),
                ),
                ("is_top_post", models.BooleanField(default=False)),
                ("is_trending", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
