# Generated by Django 5.2.7 on 2025-11-28 18:36

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BloggeApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog_post",
            name="category",
            field=models.CharField(
                choices=[
                    ("travel", "Travel"),
                    ("business", "Business"),
                    ("news", "News"),
                    ("sport", "Sport"),
                    ("mary astor", "Mary Astor"),
                ],
                default="travel",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="blog_post",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
