# Generated by Django 5.2.7 on 2025-12-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BloggeApp", "0002_alter_blog_post_category_alter_blog_post_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="is_clicked",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="blog_post",
            name="category",
            field=models.CharField(
                choices=[
                    ("travel", "Travel"),
                    ("business", "Business"),
                    ("news", "News"),
                    ("sport", "Sport"),
                    ("health", "Health"),
                    ("food", "Food"),
                    ("mary astor", "Mary Astor"),
                ],
                default="travel",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="blog_post",
            name="content",
            field=models.TextField(),
        ),
    ]
